config/routes.rb
MyFirstProjectServer::Application.routes.draw do
  get "main/index"
  root to: "main#index"

  resources :inquiries, only: [:show, :new, :create, :index]
  match '/inquiries', controller: :inquiries, action: :options, constraints: {method: 'OPTIONS'}
  match '/inquiry', controller: :inquiries, action: :options, constraints: {method: 'OPTIONS'}
  match '/inquiry/:id', controller: :inquiries, action: :options, constraints: {method: 'OPTIONS'}
  match '/inquiries/:id', controller: :inquiries, action: :options, constraints: {method: 'OPTIONS'}
end

app/models/inquiry.rb
class Inquiry < ActiveRecord::Base
  attr_accessible :description, :title, :data
  attr_accessor :data
  after_save :save_file

  private
  def save_file
    if data
      File.open("#{Rails.root}/public/images/#{self.id}.jpg", "w+") do |f|
        f.write Base64.decode64(data).force_encoding('UTF-8')
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  after_filter :cors_set_access_control_headers

  protected
  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS, PUT'
    headers['Access-Control-Max-Age'] = "1728000"
  end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  def index
    render json: Inquiry.all
  end

  def show
    render json: Inquiry.find(params[:id])
  end

  def new
    @inquiry = Inquiry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @inquiry }
    end
  end

  def create
    @inquiry = Inquiry.new(params[:inquiry])

    if @inquiry.save
      render json: @inquiry, status: :created, location: @inquiry
    else
      render json: @inquiry.errors, status: :unprocessable_entity
    end
  end

  def options
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS, PUT. DELETE'
    headers['Access-Control-Allow-Headers'] = 'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version'
    headers['Access-Control-Max-Age'] = '1728000'
    render :text => '', :content_type => 'text/plain'
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/inquiries/_form.html.erb
<%= form_for(@inquiry) do |f| %>
  <% if @inquiry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inquiry.errors.count, "error") %> prohibited this inquiry from being saved:</h2>

      <ul>
      <% @inquiry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inquiries/edit.html.erb
<h1>Editing inquiry</h1>

<%= render 'form' %>

<%= link_to 'Show', @inquiry %> |
<%= link_to 'Back', inquiries_path %>

app/views/inquiries/index.html.erb
<h1>Listing inquiries</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @inquiries.each do |inquiry| %>
  <tr>
    <td><%= inquiry.title %></td>
    <td><%= inquiry.description %></td>
    <td><%= link_to 'Show', inquiry %></td>
    <td><%= link_to 'Edit', edit_inquiry_path(inquiry) %></td>
    <td><%= link_to 'Destroy', inquiry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Inquiry', new_inquiry_path %>

app/views/inquiries/new.html.erb
<h1>New inquiry</h1>

<%= render 'form' %>

<%= link_to 'Back', inquiries_path %>

app/views/inquiries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @inquiry.title %>
</p>

<p>
  <b>Description:</b>
  <%= @inquiry.description %>
</p>


<%= link_to 'Edit', edit_inquiry_path(@inquiry) %> |
<%= link_to 'Back', inquiries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyFirstProjectServer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>